name: AKHansen
favicon: null
layout_spectrum: 0.36857
typography_spectrum: 0.25209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8877773294225335
  lightness: 0.291582333156839
  saturation: 0.2925407651346177
  rhythmicContrast: 0.41337864147499204
purpose: []
